name: GamerulesManager
version: 2.1
main: me.ted2001.gamerulesmanager.GameruleManager
api-version: 1.13
authors: [ Ted_2001 ]
description: Manage worlds gamerules via gui.
commands:
  gamerule:
    description: Open GUI Manager.
    permission: gamerulemanager.use
    aliases: [mgamerule,ggamerule,gamerules,gamerulemanager]
